<a href="https://colab.research.google.com/github/rajgupt/dl-notebooks/blob/main/pytorch/1_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

Define 

In [2]:
torch.tensor([[1,2],[3,4]])

tensor([[1, 2],
        [3, 4]])

In [13]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
a = torch.rand(2,3)
a

tensor([[0.3265, 0.2595, 0.2719],
        [0.8182, 0.3193, 0.4059]])

In [11]:
arr = np.random.rand(2,3)
torch.from_numpy(arr)

tensor([[0.2121, 0.4179, 0.4043],
        [0.4073, 0.3492, 0.8544]], dtype=torch.float64)

In [12]:
torch.rand_like(a)

tensor([[0.2521, 0.5133, 0.4061],
        [0.3766, 0.4922, 0.8233]])

In [14]:
a.shape

torch.Size([2, 3])

In [15]:
a.dtype

torch.float32

In [16]:
a.device

device(type='cpu')

Play with the Structure

In [20]:
a

tensor([[0.3265, 0.2595, 0.2719],
        [0.8182, 0.3193, 0.4059]])

In [23]:
a[0,:]

tensor([0.3265, 0.2595, 0.2719])

In [22]:
a[:,:1]

tensor([[0.3265],
        [0.8182]])

In [25]:
a[:1,:2]

tensor([[0.3265, 0.2595]])

In [26]:
torch.cat([a,a,a])

tensor([[0.3265, 0.2595, 0.2719],
        [0.8182, 0.3193, 0.4059],
        [0.3265, 0.2595, 0.2719],
        [0.8182, 0.3193, 0.4059],
        [0.3265, 0.2595, 0.2719],
        [0.8182, 0.3193, 0.4059]])

In [27]:
torch.cat([a,a,a],dim=1)

tensor([[0.3265, 0.2595, 0.2719, 0.3265, 0.2595, 0.2719, 0.3265, 0.2595, 0.2719],
        [0.8182, 0.3193, 0.4059, 0.8182, 0.3193, 0.4059, 0.8182, 0.3193, 0.4059]])

In [28]:
a.reshape(3,2)

tensor([[0.3265, 0.2595],
        [0.2719, 0.8182],
        [0.3193, 0.4059]])

In [29]:
a.flatten()

tensor([0.3265, 0.2595, 0.2719, 0.8182, 0.3193, 0.4059])

Arithmetic

In [30]:
a + a 

tensor([[0.6529, 0.5190, 0.5438],
        [1.6365, 0.6387, 0.8118]])

In [31]:
a**2

tensor([[0.1066, 0.0674, 0.0739],
        [0.6695, 0.1020, 0.1647]])

In [35]:
a @ a.T

tensor([[0.2479, 0.4604],
        [0.4604, 0.9362]])

In [38]:
a.sum(dim=0), a.sum(dim=1)

(tensor([1.1447, 0.5789, 0.6778]), tensor([0.8579, 1.5435]))

In-place operation 

In [40]:
a.add_(1)

tensor([[1.3265, 1.2595, 1.2719],
        [1.8182, 1.3193, 1.4059]])

In [41]:
a

tensor([[1.3265, 1.2595, 1.2719],
        [1.8182, 1.3193, 1.4059]])

In [46]:
b = a.numpy()
b

array([[1.3264642, 1.2595217, 1.271909 ],
       [1.8182275, 1.3193341, 1.4058887]], dtype=float32)

In [ ]:
a